### ISSUE TITLE
Agg

### ISSUE THREAD

**Issue by tgossmann** [mathiasbockwoldt/TruSD#2]
add agg to matplotlib and ensure compt with cluster engines (e.g. no screen)

**Comment by tgossmann** [comment]
import matplotlib
matplotlib.use('agg')

Correct solution?

**Comment by mathiasbockwoldt** [comment]
Yes, that is correct. I added some more logic, because with `agg`, you can't `plt.show()` anything. Starting with commit 
7246815, the script uses `agg` if the environmental variable `DISPLAY` is not available. Otherwise the default is used.
